services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitness-micro-user
      POSTGRES_USER: nikhilagrawal
      POSTGRES_PASSWORD: nikhil@123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nikhilagrawal"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - fitness-network

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - fitness-network

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    networks:
      - fitness-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: keycloak
    command: start-dev
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    networks:
      - fitness-network

  configserver:
    build:
      context: ./configserver
    container_name: configserver
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - fitness-network

  eureka:
    build:
      context: ./eureka
    container_name: eureka
    restart: unless-stopped
    depends_on:
      - configserver
    ports:
      - "8761:8761"
    networks:
      - fitness-network

  userservice:
    build:
      context: ./userservice
    container_name: userservice
    restart: unless-stopped
    depends_on:
      - postgres
      - configserver
      - eureka
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/fitness-micro-user
      DB_USERNAME: nikhilagrawal
      DB_PASSWORD: nikhil@123
    ports:
      - "8081:8081"
    networks:
      - fitness-network

  activityservice:
    build:
      context: ./activityservice
    container_name: activityservice
    restart: unless-stopped
    depends_on:
      - mongodb
      - kafka
      - configserver
      - eureka
    ports:
      - "8082:8082"
    networks:
      - fitness-network

  aiservice:
    build:
      context: ./aiservice
    container_name: aiservice
    restart: unless-stopped
    depends_on:
      - mongodb
      - kafka
      - configserver
      - eureka
    environment:
      GEMINI_KEY: ${GEMINI_KEY}
    ports:
      - "8083:8083"
    networks:
      - fitness-network

networks:
  fitness-network:
    external: true

volumes:
  postgres-data:
    external: true

  mongodb_data:
    external: true