spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/fitness-activity

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: activity-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.use.type.headers: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

kafka:
  topic:
    name: activity-topic

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
    key: ${GEMINI_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO